---
- hosts: k3s_agents
  become: True
  vars:
    k3s_server_url_or_ip: "{{ groups['k3s_servers'][0] }}"
  tasks:
  - name: Create kubeconfig
    shell: |
      cat /etc/rancher/k3s/k3s.yaml \
      | sed -e 's/127\.0\.0\.1/{{ k3s_server_url_or_ip }}/' \
      > /tmp/k3s.yaml
    delegate_to: "{{ groups['k3s_servers'][0] }}"

  - name: Fetch kubeconfig from k3s_server
    fetch:
      src: /tmp/k3s.yaml
      dest: "{{ playbook_dir }}/../files/"
      flat: True
    delegate_to: "{{ groups['k3s_servers'][0] }}"

  - name: Create target dir
    file: path=/etc/rancher/k3s/ state=directory

# see files/kilo-k3s.yaml L172
  - name: Copy kubeconfig to k3s_agents
    copy:
      src: "{{ playbook_dir }}/../files/k3s.yaml"
      dest: /etc/rancher/k3s/k3s.yaml

  - name: Install K3S agent, if it doesnt exist k3s
    shell: |
      curl -sfL https://get.k3s.io | sh -
    args:
      creates: /usr/local/bin/k3s
      warn: False
    environment:
      K3S_URL: "https://{{ k3s_server_url_or_ip }}:6443"
      K3S_TOKEN: "{{ k3s_cluster_secret }}"
      INSTALL_K3S_EXEC: "agent"

